### ISSUE TITLE
enhancement: disable admin_notice

### ISSUE THREAD

**Issue by mitchelldmiller** [salcode/stop-emails#14] opened 2018-02-12 16:29 UTC
Hello Sal:
I just tested Stop Emails with my [Quick Mail](https://github.com/mitchelldmiller/quick-mail-wp-plugin) plugin, on a site using [Mailgun](https://github.com/mailgun/wordpress-plugin) plugin to send mail.

![stop_emails](https://user-images.githubusercontent.com/6073590/36107235-6a20e572-0fe7-11e8-969e-3f547f850f96.png)

Message was sent, despite warning.

Please consider adding a setting to disable admin notice.

Best wishes,
Mitchell

**Comment by salcode** [comment] 2018-02-12 19:31
HI @mitchelldmiller

Thanks for the report about the plugin conflict.

If I understand you properly, this problem surfaced when using your plugin **Quick Mail**.

However, it sounds like the problem is how Stop Emails and the [Mailgun](https://github.com/mailgun/wordpress-plugin) plugin interact.

I'm hesitant to add a setting (or a filter) to disable the admin notice because I really want to avoid the situation where emails are being stopped and the website owner is oblivious to it.

Can you help me understand how disabling the Stop Emails admin notice would help in your situation?

Is your thought to disable the message on a specific site? or add code to your plugin to disable the notice?  or something else I haven't thought of? 😀 

I'd like to help address this problem but I also want to be cautious in what changes I make.

Thanks again for bringing this up and I would greatly appreciate your further feedback.

Thanks.

**Comment by mitchelldmiller** [comment] 2018-02-12 20:58
Hello @salcode,
Sorry for not being clear.

Somebody using Stop Emails with Quick Mail would see admin notice and think mail was disabled.

Similar result using [Quick Mail](https://github.com/mitchelldmiller/quick-mail-wp-plugin) without Mailgun. Only difference was a dumped array with message info in PHP error log.

![screen shot 2018-02-12 at 3 37 43 pm](https://user-images.githubusercontent.com/6073590/36118597-985f987e-100b-11e8-87ec-502bb85f76f8.png)

Quick Mail sends message using wp_mail(), despite warning.

Best wishes,
Mitchell

**Comment by salcode** [comment] 2018-02-13 02:56
Hi @mitchelldmiller,

I installed [Quick Mail](https://wordpress.org/plugins/quick-mail/) and [Stop Emails](https://wordpress.org/plugins/stop-emails/) on a test site running WordPress `4.9.4`.  I used WP CLI to download, install, and activate the plugins.

```
$ wp plugin install quick-mail stop-emails --activate
```

In **Quick Mail Settings**, I checked `Grant Quick Mail permission to use your email address.`

and clicked `Save Options`

<img width="753" alt="screenshot 2018-02-12 21 42 06" src="https://user-images.githubusercontent.com/5194588/36131002-a4352632-103d-11e8-925f-2f3b02ab6725.png">

I'm using Local by Flywheel which comes with [MailHog](https://github.com/mailhog/MailHog), so I opened that browser tab.

Then using **Tools** > **Quick Mail**, I created a test mail with subject "test" and  message "test".

<img width="509" alt="screenshot 2018-02-12 21 45 10" src="https://user-images.githubusercontent.com/5194588/36131078-0e6679e8-103e-11e8-8f81-19b7e200a329.png">

then I clicked `Send Mail`.

I did not see any emails in MailHog (**expected result**)

<img width="406" alt="screenshot 2018-02-12 21 46 51" src="https://user-images.githubusercontent.com/5194588/36131118-46307900-103e-11e8-9a51-ae41e50583ab.png">

Then I changed the Stop Email setting to log outgoing emails

<img width="585" alt="screenshot 2018-02-12 21 47 54" src="https://user-images.githubusercontent.com/5194588/36131138-673fe810-103e-11e8-9fea-09da8640a0a9.png">

Once again, I clicked `Send Mail`

Still no mail in MailHog but this time the email was logged to my error log.  (**expected result**)

```
[13-Feb-2018 02:48:40 UTC] Array
(
    [to] => Array
        (
            [0] => Array
                (
                    [0] => test@ironcodestudio.com
                    [1] => 
                )

        )

    [cc] => Array
        (
        )

    [bcc] => Array
        (
        )

    [header] => Date: Tue, 13 Feb 2018 02:48:40 +0000
From: admin <dev-email@flywheel.local>
Reply-To: admin <dev-email@flywheel.local>
Message-ID: <adc0e92ea61ec5eefdd6cdd7397df698@genesis.test>
X-Mailer: PHPMailer 5.2.22 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8

    [body] => Test

)
```

Finally, I deactivated the Stop Emails plugin

```
$ wp plugin deactivate stop-emails
```

and clicked `Send Mail` once again.

This time the email does appear in MailHog.  (**expected result**)

<img width="559" alt="screenshot 2018-02-12 21 51 32" src="https://user-images.githubusercontent.com/5194588/36131276-f6927474-103e-11e8-97c6-48bd55b936c4.png">

I suspect there is another plugin conflict is causing the problem (e.g. the MailGun may be overriding email in a way that overrides Stop Emails).  Of course, other factors can vary (or I may be missing something) so if you have a set of reproducible steps to recreate the error, I'd be happy to look into this further.

**Comment by salcode** [comment] 2018-02-13 03:12
@mitchelldmiller 

If you want to make sure the Stop Emails plugin does **not** run, you can add some code to deactivate it, if the plugin is active.

This code checks for the Stop Emails plugin every time a backend page loads, if the plugin is active it deactivates it.

```
function deactivate_stop_emails_if_active() {
	$active_plugins = get_option('active_plugins');
	$result = array_search( 'stop-emails/stop-emails.php', $active_plugins, true );
	if ( false !== $result ) {
		deactivate_plugins( 'stop-emails/stop-emails.php' );
	}
}
add_action( 'admin_init', 'deactivate_stop_emails_if_active' );
```

**Comment by mitchelldmiller** [comment] 2018-02-15 21:26
Hello @salcode ,
Thank you for testing.
I tested with Quick Mail's WP-CLI command from [version_342 branch](https://github.com/mitchelldmiller/quick-mail-wp-plugin/tree/version_342) which has better messages.
![qm-cli](https://user-images.githubusercontent.com/6073590/36281531-f68f3956-126b-11e8-99f3-4d14d70965f0.png)

Same result. Mailgun is not affected.
If I deactivate Mailgun, and send a link:
`wp quick-mail me@example.com you@example.com https://wheredidmybraingo.com/disclaimer/ "Blog Disclaimer"`

The screen fills with error_log output. You might want to replace the error_log() if WP-CLI is active.

>If you want to make sure the Stop Emails plugin does not run, you can add some code to deactivate it, if the plugin is active.

This would confuse your plugin's users. I will add _Stop Emails_ info to FAQ.

Best wishes,
Mitchell

**Comment by salcode** [comment] 2018-02-16 18:10
Thanks for the information.  I just opened #15 regarding behavior via WP CLI. 👍

**Comment by mitchelldmiller** [comment] 2018-02-21 23:07
Hello @salcode ,
Stop Emails does not prevent [SparkPost plugin](https://github.com/SparkPost/wordpress-sparkpost) from sending mail. 

I added info to latest [Quick Mail readme](https://github.com/mitchelldmiller/quick-mail-wp-plugin/blob/version_342/readme.txt#L144).

Best wishes,
Mitchell

**Comment by salcode** [comment] 2018-02-22 01:43
Thanks @mitchelldmiller, I've added SparkPost to [wiki/Known-Incompatible-Plugins](https://github.com/salcode/stop-emails/wiki/Known-Incompatible-Plugins)

**Comment by salcode** [comment] 2018-12-14 21:22
This conversation went in a helpful direction and allowed me to add some new entries to the [Known Incompatible Plugins](https://github.com/salcode/stop-emails/wiki/Known-Incompatible-Plugins) in the Wiki.

Since the original focus of the issue, "disable admin_notice", is not a change I'm going to make, I'm going to close this issue.

**Closed by salcode** 2018-12-14 21:22 UTC
